name: Deployment Workflow
on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy bot
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: 45.7.231.47
        username: root
        key: ${{ secrets.SSH_SECRET }}
        port: 22222
        script: |
          cd ybot
          git pull origin master
          pip3 install -r requirements.txt
          systemctl restart ybot
          systemctl status ybot
