name: Deployment Workflow
on:
  push:
    branches: [master]

jobs:
  clone_repo:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: test ssh connection
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: 45.7.231.47
        username: root
        key: ${{ secrets.SSH_SECRET }}
        port: 22222
        script: |
          cd ybot
          git pull origin master
          git status
